server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskflow}
    username: ${DB_USERNAME:taskflow}
    password: ${DB_PASSWORD:taskflow}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
